name: run all tests

on:
  push:
    branches: ["ci/run-full-test-suite"]

jobs:
  full_test_suite:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: restore poetry cache
        uses: actions/cache@v2
        id: restore-poetry
        with:
          path: .poetry
          key: ${{ runner.os }}-poetry

      - name: restore vendor cache
        uses: actions/cache@v2
        id: restore-vendor
        with:
          path: .poetry
          key: ${{ runner.os }}-poetry

      - name: install LabLib
        if: steps.restore-poetry.outputs.cache-hit != 'true'
        run: |
          .\start.ps1 install

      - name: get dependencies
        if: steps.restore-vendor.outputs.cache-hit != 'true'
        run: |
          .\start.ps1 get-dependencies

      # - name: run all tests
      #   run: |
      #     .\start.ps1 test

      - name: save vendor dependencies cache
        if: steps.restore-vendor.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-vendor

      - name: save poetry cache
        if: steps.restore-poetry.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-poetry
        with:
          path: .poetry
          key: ${{ runner.os }}-poetry
